// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WindowsFormsApp1;
//
//    var adat = Adat.FromJson(jsonString);

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using WindowsFormsApp1;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Adat
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("cvv")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Cvv { get; set; }

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Alive")]
        public bool Alive { get; set; }
    }

    public partial class Adat
    {
        public static Adat[] FromJson(string json) => JsonConvert.DeserializeObject<Adat[]>(json, WindowsFormsApp1.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Adat[] self) => JsonConvert.SerializeObject(self, WindowsFormsApp1.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}

